from emoji import emojize


class Emoji:
    robot = emojize(':robot:', language='alias')
    eyes = emojize(':eyes:', language='alias')
    eye = emojize(':eye:', language='alias')
    email = emojize(':email:', language='alias')
    diamond = emojize(':gem:', language='alias')
    lock = emojize(':closed_lock_with_key:', language='alias')
    email = emojize(':incoming_envelope:', language='alias')
    worning = emojize(':warning:', language='alias')
    clock = emojize(':alarm_clock:', language='alias')
    point = emojize(':exclamation:', language='alias')
    bags = emojize(':shopping_bags:', language='alias')
    flash = emojize(':flashlight:', language='alias')
    check = emojize(':ballot_box_with_check:', language='alias')
    plug = emojize(':electric_plug:', language='alias')
    gift = emojize(':gift:', language='alias')
    blue_diamond = emojize(':small_blue_diamond:', language='alias')
    orange_diamond = emojize(':small_orange_diamond:', language='alias')
    money = emojize(':money_bag:', language='alias')
    bell = emojize(':bell:', language='alias')
    card = emojize(':credit_card:', language='alias')
    sos = emojize(':sos:', language='alias')
    netflix = emojize(':movie_camera:', language='alias')
    back = emojize(':back:', language='alias')
    spotify = emojize(':headphones:', language='alias')
    infinity = emojize(':video_camera:', language='alias')
    dazn = emojize(':soccer:', language='alias')
    house = emojize(':house:', language='alias')
    p = emojize(':parking:', language='alias')
    a = emojize(':a:', language='alias')
    euro = emojize(':euro:', language='alias')
    x = emojize(':x:', language='alias')
    flag = emojize(':beginner:', language='alias')
    check_1 = emojize(':heavy_check_mark:', language='alias')